apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    name: mongo-express-service
    app: WebUI
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30007
  selector:
      name: mongo-express-pod
      app: WebUI